version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD} --save 60 1
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis:/data

  rabbitmq:
    image: rabbitmq:3.7
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "${RABBITMQ_PORT}:5672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  app:
    build: .
    depends_on:
      - postgres
      - redis
      - rabbitmq
    restart: always
    environment:
      AMQP_URL: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis
      TELEGRAM:
      GOOGLE:
      SPREADSHEET:
      TIMEZONE:
      DB_UPDATE_PASSWORD:
    volumes:
      - app_tmp:/app/tmp

volumes:
  postgres:
  redis:
  rabbitmq:
  app_tmp:
