version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD} --save 60 1
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./.data/redis:/data

  nocodb:
    image: nocodb/nocodb:latest
    depends_on:
      - db
    environment:
      NC_DB: "pg://postgres:${POSTGRES_PORT}?u=${POSTGRES_USER}&p=${POSTGRES_PASSWORD}&d=nocodb"
    ports:
      - "${NOCODB_PORT}:8080"
