version: 1

formatters:
  colored:
    (): coloredlogs.ColoredFormatter
    format: '%(asctime)s [%(levelname)s] (%(name)s) @ %(filename)s:%(lineno)d - %(message)s'
  simple:
    format: '%(asctime)s [%(levelname)s] (%(name)s) @ %(filename)s:%(lineno)d - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    formatter: colored

root:
  level: INFO
  handlers: [console]

disable_existing_loggers: False